#include <stdio.h>
// Problem #2
// Each new term in the Fibonacci sequence is generated by 
// adding the previous two terms. By starting with 1 and 2, 
// the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not 
// exceed four million, find the sum of the even-valued terms.

int main( void )
{
    // Intialize the first 2 terms
    int t_1 = 0;
    int t_2 = 1;
    int sum = 0;
    // Intialize the 3rd term
    int nxt_t = t_1 + t_2;

    while (nxt_t < 4000000)
    {
        // Put the value of 2nd term inside 1st variable
        t_1 = t_2;
        // Put the value of next term inside 2st variable
        t_2 = nxt_t;
        // Find the next term 
        nxt_t = t_1 + t_2;
        // Find all even numbers
        if (nxt_t % 2 == 0)
            // Add all even numbers to each other
            sum = sum + nxt_t;
    }
    printf("%d",sum);
    return sum;
}