# Problem #2
# Each new term in the Fibonacci sequence is generated by 
# adding the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

function fibonacci(terms)
    first_term = 0
    second_term = 1
    next_term  = first_term  + second_term
    sum  = 0
    for i in 0:terms
        next_term  = first_term  + second_term
        first_term = second_term
        second_term = next_term
        if next_term % 2 == 0 
            sum = next_term + sum
        end
    end
    println(sum)
end

fibonacci(32)
